ideascube/ideascube

blog/templates/blog/content_form.html
ideasbox/conf/base.py
ideasbox/conf/bwagiriza.py
ideasbox/conf/kavumu.py
ideasbox/conf/makamba.py
ideasbox/conf/musasa.py
ideasbox/management/commands/dummydata.py
ideasbox/models.py
ideasbox/settings.py
ideasbox/templates/form-fullpage.html
ideasbox/templates/ideasbox/user_detail.html
ideasbox/templates/ideasbox/user_form.html
ideasbox/tests/test_models.py
library/templates/library/book_form.html
library/templates/library/specimen_form.html

This PR also:
- fixes model mixins that was not inheriting from `models.Model`, so fields was not active
- fixes `form-fullpage.html` template that was overriding `title` block
- introduces a `user.public_fields` method, allowing to loop over user fields, even with a custom user model
If it's better, I can split this into other PRs. :)

Add per box settings (cf #41)

---

blog/tests/test_views.py
ideasbox/conf/base.py
ideasbox/static/ideasbox/main.css
ideasbox/templates/form-fullpage.html
ideasbox/templates/ideasbox/form_confirm_delete.html
ideasbox/templates/ideasbox/includes/footer.html
ideasbox/templates/ideasbox/user_confirm_delete.html
ideasbox/templatetags/ideasbox_tags.py
ideasbox/tests/test_templatetags.py
ideasbox/tests/test_views.py
ideasbox/urls.py
library/templates/library/book_confirm_delete.html
library/templates/library/specimen_confirm_delete.html
library/tests/test_views.py
search/templates/search/box.html
search/tests/test_views.py

Ref: #56
This PR just adds a select lang switcher in the footer, but there are two tricks:
- firstly, as it adds a form in every page, I've needed to add ids to every form, in order to make them selectable in unittests, which create a lot of noise in the diff
- secondly, as we are using i18n URLs, we needed to workaround a limitation of the Django view: if we just give the current URL as "next" parameter, it will never work, because the URL contains the i18n prefix (for example `/en/`, so the Django view will set the new lang, then redirect to the next URL, which contains the i19n prefix, so will be caught by the i18n middleware, which at its turn will set the current language (so using the initial language)

Add lang switcher in footer (fix #56)

---

debian/control

This change allows to build cleanly on an Ubuntu trusty PPA (trusty has dh-virtualenv 0.6.1)

Added python-pytest to build-depends.

---

ideasbox/conf/base.py
ideasbox/serveradmin/tests/test_views.py
ideasbox/serveradmin/views.py
requirements-dev.txt

When defining a service in settings, it's possible to override the way to interact the service, this was clashing with the `status` key.

Fix service getter clashing with status key

---

ideasbox/static/ideasbox/main.css

On ipad chrome rendering engine does not support flexbox and needs proper prefixing.

Fix ios chrome layout issues

---

CONTRIBUTING.md
README.md
docs/install.md

Here is a proposal around documentation for contributors.
Here are planned changes:

CONTRIBUTING.md contains contributor guide

---

AUTHORS.md
LICENSE.md
README.md

setup.py already has "license" but LICENSE file was missing. Added it. Mentioned it in README.
Can you check license, date and copyright holder?

README mentions license and links to LICENSE file.

---

CONTRIBUTING.md

To execute without errors "make devinstall" I had to install these additionnal packages. Installing 'libxml2-dev' only wasn't enough.
It may be because I'm running an old 12.04 ubuntu desktop.
The log message is here:
https://zerobin.net/?1b0815e147ec6d05#WNN8th4y3K9FUGEHGUBakUo2KqzN5l3tJHzmQXEi25s=

Adds two packages (libxml2-dev libxslt1-dev) to dependencies.

---

.travis.yml
Makefile
pytest.ini

The coverage report takes a lot of space, which can distract from the actual test results.
This commit makes it so that running "py.test" or "make test" doesn't check for coverage any more at all.
A new "make testcov" target is introduced, which both runs the tests and reports coverage.

tests: Don't run coverage by default

---

.travis.yml
docs/contributing.md
ideascube/conf/base.py
ideascube/serveradmin/templates/serveradmin/index.html
ideascube/serveradmin/templates/serveradmin/wifi.html
ideascube/serveradmin/templates/serveradmin/wifi_history.html
ideascube/serveradmin/tests/__init__.py
ideascube/serveradmin/tests/test_views.py
ideascube/serveradmin/tests/test_wifi.py
ideascube/serveradmin/urls.py
ideascube/serveradmin/views.py
ideascube/serveradmin/wifi.py
ideascube/static/ideascube/js/ideascube.js
ideascube/static/ideascube/main.css
requirements-dev.txt
requirements.txt

Here is wifi management for the admin interface.
It is still a work in progress, so don't merge it just yet.
However, it does enough that it's worth sharing, if only to enable early review.
Also, note that I'll be rebasing this branch, so if you fetch it locally be prepared to have to force things a bit. :wink: 
What's done and missing:
Do we want to support other types of network security? WEP just shouldn't be used any more now, and I'm not sure the various "enterprise" types are very useful for our target. :smiley: 
Do we want to support connecting to a hidden network? (that is, one which does not advertise its SSID)
Is there anything else the admin app should be able to do with Wifi networks?
Screenshots of how it looks like are at: https://bochecha.fedorapeople.org/ideascube/

Wifi management

---

ideascube/models.py
ideascube/tests/test_views.py
ideascube/views.py

We don't need to know about a user's real name, the (hopefully anonymous) serial is enough for our data collection purposes.
I'm only hiding the fields @barbayellow explicitly mentioned to me. However, there seems to be other potentially private informations in other fields, that we probably shouldn't have in CSV exports. Things like the family or marital status, or even the gender.
In any case, those would just need to be added to the new `User.PRIVATE_DATA` field, and then they would not be exported to CSVs any more.

csv: Do not export private user information

---

ideascube/serveradmin/wifi.py

On some openrating systems (e.g Mac OS X) DBus isn't available.
Therefore, the dbus-python module can't be built and installed.
With this commit, all that happens is that the Wi-Fi management page is not available, dsplaying the "Wi-Fi is disabled" message, instead of spewing 500 errors.
Fix #218

wifi: Don't crash if dbus can't be imported

---

debian/control
debian/rules

With this, we can build a Debian package for ideascube with the [sbuild](https://wiki.debian.org/sbuild) command, and with correct dependencies.
`sbuild` allows building the package in a chroot, populated only with packages from the Jessie repos (which entirely avoids issues like the one @fheslouin regularly has with libjpeg), in a completely unattended and (almost) reproducible way.
This in turn will allow us to build packages in a [Buildbot](https://buildbot.net/). And in fact, I have a local Buildbot which just successfully built a Debian package for Ideascube, which should make @barbayellow happy. :smile:

Debian packaging fixes

---

ideascube/serveradmin/backup.py
ideascube/serveradmin/tests/test_views.py

When a Backup() object is instantiated, ensure the backup root directory
exists. It is implicitly created by the create() method, but not by
other methods such as load().
Signed-off-by: Loic Dachary <loic@dachary.org>

server admin: ensure backup root exists (fix #244)

---

ideascube/serveradmin/systemd.py
ideascube/serveradmin/tests/__init__.py
ideascube/serveradmin/tests/test_systemd.py
ideascube/serveradmin/tests/test_views.py

The problem is that the stdout and stderr of a subprocess.Popen call are bytes, not unicode.
And then in the code, we mix that with string literals... which were bytes in Python2, but unicode in Python3.
The unit tests never found the problem, because we mock the Popen and its stdout/stderr, replacing the latter by StringIO.
And in Python3, StringIO take unicode, not bytes, so everything was just fine for the unit tests.

systemd: Fix bytes/unicode issue

---

ideascube/serveradmin/wifi.py

In cc2dcd1e4da394c7bff98e499649d3cfb238cd24, we introduced a dirty hack to work around the fact that we talk to NetworkManager over DBus using an asynchronous API, but we need a synchronous response about whether we connected or not.
To refresh our collective memory, after that change we now just try checking whether we are connected over and over again, waiting one second between each check.
That loop either stops when we are connected, or after 6 attempts, whichever comes first.
And if after 6 attempts we're still not connected, then we consider that NM failed to connect, and we just delete the NM Connection object.
After that, we try to display the wifi page, with an error about how we couldn't connect.
And when displaying the wifi page, we try to check whether we are connected to each …

wifi: Fix traceback

---

ideascube/conf/kb.py

I think we can now remove the STORAGE_ROOT variable from the config file, indeed, we are now using a symlink from /var/ideascube pointing to /media/hdd/ideascube (koombook only). This is also fixing the process of installation as I had rights conflicts with the SQLite DB. I have tested it on KoomBook and it's working fine!

Remove STORAGE_ROOT var from kb.py

---

ideascube/serveradmin/wifi.py

I would suggest to increase the number of attempts to 12. Indeed, the connexion sometime FAILED because the number is too low. After several test it seems that 12 is a good enough value. There is still some random FAILING but it is better.

Increase number of attemps on wifi module

---

ideascube/serveradmin/catalog.py
ideascube/utils.py

Just remove sys.std(out|err).write calls to print and printerr.
No functional changes.

Use print instead of sys.std(out|err).write.

---

ideascube/library/migrations/0005_merge.py
ideascube/mediacenter/migrations/0009_merge.py
ideascube/serveradmin/catalog.py
ideascube/serveradmin/tests/test_catalog.py

This PR does four things:
- when installing a zim, always override any preexisting content (and do not fail)
- persist cache as soon as a package is marked as installed/removed
- download all packages then install all packages instead of doing download/install by package
- catch download/install/remove errors and continue to the next id to be processed (instead of failing)
cf #326

Catalog: more defensive approach

---

pytest.ini

Our database is in memory, so it doesn't have any impact on execution time.

Use a fresh database for every test

---

ideascube/serveradmin/catalog.py
ideascube/serveradmin/management/commands/catalog.py
ideascube/serveradmin/tests/test_catalog.py

Eventually, we're going to a place where we backup the list of installed content, but not the actual installed content.
Thus, when restoring from a backup, we will need a way to reinstall the content that the catalog thinks is installed.
More generally, this could also be useful if for some reason a package had been badly installed.

catalog: Allow reinstalling packages

---

ideascube/blog/templates/blog/index.html
ideascube/blog/tests/test_views.py
ideascube/blog/views.py
ideascube/library/templates/library/index.html
ideascube/library/tests/test_views.py
ideascube/library/views.py
ideascube/mediacenter/templates/mediacenter/index.html
ideascube/mediacenter/tests/test_views.py
ideascube/mediacenter/views.py
ideascube/mixins.py
ideascube/search/templates/search/order_by.html

Fix #363 fix #368.
- adds a "order by" box in the mediacenter, blog and library pages, which shows the current ordering, and the other available
- when clicking on the active ordering, the sort is reversed
- the possibility to define for each home page which orders are possible, including the default sort for each one
Preview:

Add "order by" selector in list views (fix #363 fix #368)

---

ideascube/conf/base.py
ideascube/serveradmin/backup.py
ideascube/serveradmin/management/commands/backup.py
ideascube/serveradmin/tests/conftest.py
ideascube/serveradmin/tests/test_backup.py
ideascube/serveradmin/tests/test_views.py

Zip format is generally a pain to deal with (hello non-ascii characters).
In addition, we're about to add filtering of which files to backup and which files to ignore, which is trivial to do with the tarfile module, but much harder with the zipfile one.
To keep things simpler, we've decided to remove Zip support.
Zip backups are still supported for restore, though.
[CONFIG_CHANGE]
- zip is no more supported for BACKUP_FORMAT.
- Default value for BACKUP_FORMAT as change from 'zip' to 'gztar'
This is part of #342

Drop support of creating zip backup.

---

ideascube/mediacenter/templates/mediacenter/document_detail.html

Use the document's kind instead of 'Document' for the Download buton

---

ideascube/conf/base.py

So that an active session is not deleted.

Save session at every request (fix #417)

---

ideascube/conf/idb_eth_melkadida.py
ideascube/tests/test_settings.py

We regularly make little syntax errors in the config files, leading to lots of pain down the road.
With this test, config files will be validated at each push to the ideascube repository, which should make us happier.
And in fact, it actually found a broken config!
That config is old, and probably worked at the times of Python 2, but we moved to Python 3 since then. Good thing that box was never updated. :-/
Fixes #395

Test all the config files

---

ideascube/library/utils.py

Fix #433.
- Strip the isbn to be sure there is no space.
- Decode the request return as json parse str, not bytes
- If we don't want to fail in any way, do not return None.

Fix book's import from isbn.

---

conftest.py
ideascube/migrations/0009_add_a_system_user.py
ideascube/models.py
ideascube/tests/test_models.py
ideascube/tests/test_views.py

This user won't be allowed to log in, so it won't be used by any physical person behind their screen.
However, it will be useful to change in-db settings in migrations or in a command-line too, since Setting instances require an actor.
It is a hidden user, to be used exclusively by Ideascube itself.

Add a system user

---

conftest.py

The default Handler from logging store "in cache" the sys.stderr when it's
create.
When capsys from py.test try to mock sys.stderr, it is to late.
But logging has a Handler who always print to sys.stderr and do not cache
it.
We configure logging to use it, then, mocking from py.test works correctly.

Correctly catch output from logging to stderr.

---

requirements.txt

We don't need to point ot our fork, now.
The reason we needed it went away as upstream merged out pull request:
berdario/resumable-urlretrieve#1

Move back to the latest upstream release of resumable-urlretrieve

---

ideascube/conf/base.py
ideascube/tests/test_models.py

IDB are overwritting this config anyway, and we don't want them
for Koombooks.

Remove language skills from default USER_FORM_FIELDS

---

ideascube/static/ideascube/main.css
ideascube/templates/index.html
ideascube/templates/two-third-third.html

This does three things:
- completely reboot media queries: they were done the wrong way (not using cascading, so rules were declared for every media query), some rules were obsolete, and some rules were just too specific; I'm not saying this is fixing every issue we can have with responsiveness, but it's much better on the tablets, and the code is much much simpler (200 lines vs 35), so easier to maintain and fix in the future
- add mhalf and thalf break point triggers (m as mobile, t as tablet, as for other rules created before): allow to better divide the screen on small sizes
- fix #447 by adding a generic padding on home cards (rtl support too)

Media queries reboot

---

conftest.py
extras/nginx/ideascube
ideascube/blog/templates/blog/content_form.html
ideascube/conf/base.py
ideascube/context_processors.py
ideascube/library/templates/library/book_card.html
ideascube/mediacenter/templates/mediacenter/document_card.html
ideascube/mediacenter/templates/mediacenter/document_detail.html
ideascube/mediacenter/templates/mediacenter/oembed.html
ideascube/templates/base.html
ideascube/templates/ideascube/includes/footer.html
ideascube/templates/ideascube/includes/form_statics.html

This moves us towards using Django's `ManifestStaticFilesStorage` which appends to the file names their hash, when running `collectstatic`, and then makes sure the requested URLs are to the URLs containing the hashes.
Once that's done, we can configure nginx to tell clients to keep these files in cache forever.
Fixes #467

Aggressively cache the static files

---

ideascube/blog/forms.py

Everybody is sleeping here, but I can't, because my brain is fixating on this media URL thing from #468.
And while working on the media, I found this fallout from the Django 1.10 upgrade.
The commit message has all the details about the problems, so let me paste it here:
```
Fix the blog content form
The form plays a trick on the 'text' field: it hides it, and creates a
nicer-looking 'content' field. When submitting the form, the content of
the 'content' field is injected into the 'text' field.
This works great, until Django 1.10.
With Django 1.10, the browser refuses to submit the form, saying the
'text' field is empty and required.
This is due to this hidden gem from the Django 1.10 release notes:
> * Required form fields now have the required HTML attribute. Set the
> …
```

Fix the blog content form

---

ideascube/search/apps.py

We have two problems with the search app currently.
The first is that if an instance of ideascube gets updated from a very old version, the migrations fail. (#456)
The second is that because the Search model is not managed by Django, if we add new fields to it then no migration gets created, which breaks the application as well as the post-migrate reindex. (#489)
The solution to both is actually quite simple: simply always drop and recreate the index table before running the migrations.
Fixes #456
Fixes #489

search: Recreate the index table before migrating

---

ideascube/mediacenter/templatetags/mediacenter_tags.py

I introduced this error in 8c536774cfe40783350f6f569eb6580e79499600.
Fixes #492

We already use the static tag in the templates

---

ideascube/blog/templates/blog/content_form.html
ideascube/monitoring/templates/monitoring/loan.html
ideascube/serveradmin/templates/serveradmin/name.html
ideascube/static/ideascube/main.css
ideascube/templates/ideascube/user_form.html

After a short training I noticed we could improve the form interface with little things:
- focus on first field by default. A user is typing when she sees the form without clicking for focus, she expects to be typing in the first box.
- it's nothing like obvious that the _content_ section is editable like other form fields when you are not used to transform readable text into editable text. Presenting a editable content as another form field may make it more obvious.

improved form ergonomy (field focus and content editing)

---

ideascube/serveradmin/catalog.py

We don't need to do that, since we use the cache from memory afterwards.
Plus, operations which modify the cache in-memory (install, remove,
clear cache, ...) will persist the cache on disk when they are done.
This means we can do less work, and it nicely fixes #496

catalog: Don't persist the cache when loading it

---

ideascube/blog/templates/blog/content_form.html
ideascube/library/templates/library/book_form.html
ideascube/library/templates/library/specimen_form.html
ideascube/mediacenter/templates/mediacenter/document_form.html
ideascube/monitoring/templates/monitoring/inventory_form.html
ideascube/monitoring/templates/monitoring/specimen_form.html
ideascube/monitoring/templates/monitoring/stockitem_form.html
ideascube/templates/form-fullpage.html
ideascube/templates/ideascube/set_password.html
ideascube/templates/ideascube/user_form.html
ideascube/templates/ideascube/welcome_staff.html

Some submit buttons were appearing in the right column of the page form.
That is confusing for a user who has ended the form and is looking to save it.

moved submit button to the end of their form

---

ideascube/serveradmin/templates/serveradmin/home_page.html
ideascube/static/ideascube/main.css

The "home page" configuration has now the possibility of clicking a label, not only the small checkbox, to add a package to the selection.
Fix #511

home page allows clicking on labels to add the package

---

ideascube/forms.py
ideascube/library/forms.py
ideascube/library/views.py
ideascube/mediacenter/views.py
ideascube/monitoring/forms.py
ideascube/monitoring/models.py
ideascube/serveradmin/catalog.py

swapped to `lazyloading` for modules that load translation on module import.
getting the language from django language processor instead of directly from the settings.

fixed translation for language switching

---

ideascube/static/ideascube/main.css

Space between box and the next title was too narrow.

fixed space for titles in forms

---

ideascube/serveradmin/wifi.py

if one of them is not user owned (fixes #551)

Handle the exception when trying to list wifi connections

---

ideascube/conf/base.py
ideascube/conf/kb.py
ideascube/serveradmin/templates/serveradmin/index.html

For now, this just brings in too much risk of filling up the disk and
bricking the box.
We can bring it back once we're confident we've made sufficient
improvements, either to the functionality itself, or to the disk
capacity.
Fixes #524

Hide the backup management

---

extras/nginx/ideascube
ideascube/conf/base.py
ideascube/serveradmin/catalog.py
ideascube/serveradmin/tests/test_catalog.py
ideascube/templates/ideascube/includes/cards/static-site.html
ideascube/views.py

This moves us to having a single NGinx configuration file to handle all the static sites we install as packages.
I'm bundling with it a few minor changes I stumbled upon while working on this.
Fixes #431

Simplify the installation of static site packages

---

ideascube/blog/tests/conftest.py
ideascube/blog/tests/factories.py
ideascube/monitoring/tests/factories.py

Found this because `make dummydata` was emitting warnings.

Use timezone-aware datetime objects

---

ideascube/conf/kb.py
ideascube/conf/kb_bdi_tv5monde.py
ideascube/conf/kb_bsfcampus.py
ideascube/conf/kb_bsfcampus_civ.py
ideascube/conf/kb_bsfcampus_cmr.py
ideascube/conf/kb_bsfcampus_sen.py
ideascube/conf/kb_cdf_fra.py
ideascube/conf/kb_civ_babylab.py
ideascube/conf/kb_esp_avanti.py
ideascube/conf/kb_eth_kytabu.py
ideascube/conf/kb_gin_conakry.py
ideascube/conf/kb_ifb_bdi.py
ideascube/conf/kb_jor_croixrouge.py
ideascube/conf/kb_mooc_cog.py
ideascube/conf/kb_nic_nicarali.py
ideascube/conf/kb_rca_alliancefrancaise.py
ideascube/conf/kb_servir_ben.py
ideascube/conf/kb_tza_ambassadeDeFrance.py
ideascube/conf/kb_usa_p2pu.py
ideascube/conf/kb_usa_wmapache.py

This simplifies the KB confs.
The target is to use only generic confs (kb, kb_bsfcampus, maybe one or two more) as much as possible.
Some confs still remain because of the IDEASCUBE_NAME, that needs to be updated before (through Ansiblecube). That will be another step.
Plus, we may tackle in another thread the LANGUAGE_CODE (using the server lang?), for now we can proceed, as it's not used for the UI (only for scripts and such; on the UI we default on browser language).
@bochecha @mgautierfr one of you can have a quick safety look? I'd like to release tomorrow morning before going to work :)
Thankss!

Clean kb conf

---

ideascube/migrations/0009_add_a_system_user.py

Always load models from the registry in migration files.
I hate the idea of touching a migration already released, but
this one prevents us from adding new properties to User.
If we load the User directly (not from registry) when creating
the user model, we'll try to create a user with column that does
not exist at the time of this migration.

Load user from migration registry when creating system user

---

ideascube/serveradmin/battery.py
ideascube/serveradmin/templates/serveradmin/battery.html
ideascube/serveradmin/views.py

This is pretty ugly, but the Koombook battery driver doesn't respect the
Linux convention for reporting the power status to sysfs.
As a result, batinfo doesn't work with it.
Since this is quite specific, I don't think it makes sense to push that
upstream to batinfo, so I opted for a workaround in our code.
Fixes #446

Workaround the bad Koombook battery driver

---

ideascube/tests/test_views.py
ideascube/views.py

Using the translated verbose names leads to nicer exports which humans
can better understand and process with their favourite spreadsheet
software.
However, it also means that an Ideascube export can't be imported back
into Ideascube without first renaming the column headers to the field
names.
@barbayellow says user exports have never been used by actual humans,
but only as backups.
Therefore, it seems to make sense to use the field names when exporting.
Fixes #655
Supercedes #656

users: Use the field names when exporting

---

ideascube/blog/templates/blog/content_card.html
ideascube/blog/tests/test_views.py
ideascube/blog/views.py

The staff really should be able to see draft articles in the blog index, as well as articles which will be published in the future.
Otherwise, it's a bit hard for them to edit them.
Fixes #528

blog: Staff should see more articles

---

Makefile

Just a few changes to the `Makefile`, hopefully making it just a tiny bit more readable.
In addition, we now remove obsolete strings from the generated `.po` files, to avoid asking translators to do unnecessary work.

Some i18n changes

---

Makefile
docs/contributing.md
docs/release_process.md

I just keep on forgetting to run the migrations on both databases, so
let's make it easier on ourselves.

Add a `migrate` make target

---

mkdocs.yml

Just to fix a warning.
There are other warnings but they come from the not up to date `yeti` theme.
There is no new version of it so we can be OK with the warnings for now or change the theme.

Update mkdocs to the new yml syntax.

---

ideascube/mediacenter/management/commands/import_medias.py
ideascube/serveradmin/catalog.py

That unicode black square makes for very pretty progress bars.
Until you change your font, and the square suddenly has space on its
left and right sides, and these spaces are unaccounted for when
calculating the width, and the line gets broken and it looks terrible.
In addition, we regularly have encoding errors because of it when
running the commands through an SSH connexion, with different locales
installed on the client and the server.
So let's go back to simplicity.

Use the `=` sign for the progress bars

---

ideascube/library/migrations/0008_library_stock.py
ideascube/library/tests/test_migrations.py

One of the things happening during this migration is that the serial
attribute of the old BookSpecimen model is becoming the barcode
attribute of the Specimen model.
Before this migration, people had to enter their books and specimens
both in the stock (StockItem/Specimen) and in the library
(Book/BookSpecimen).
Because they had to do it in both places, it is very possible that they
had a Specimen with a certain barcode, and a BookSpecimen with the same
serial. (see the first paragraph for how this field maps)
This crashes the migration, because Specimen.barcode has a unicity
constraint.
This commit ensures that the migration still works, removing the
existing StockItem and Specimen, effectively merging them with the new
Book and BookSpecimen.
Fixes #626
---
Note that this is based on …

Better handle the library to stock migration

---

ideascube/mediacenter/management/commands/clean.py
ideascube/mediacenter/tests/factories.py
ideascube/mediacenter/tests/test_clean.py

This PR add a command to remove orphan files from the mediacenter.
After discussion on PR #686, we agree that a command to remove orphan would be a better idea than
add a listener on the `post_delete` signal.
With a command we handle the delete case (#684) and the update case (#457)
Fixes #684 and Fixes #457

Add a command to remove orphan files from the mediacenter.

---

ideascube/mediacenter/management/commands/clean.py

Without this, it couldn't print its own help text when invoked without a
subcommand.

Fix the clean command

---

.travis.yml
ideascube/library/tests/test_utils.py
ideascube/library/tests/test_views.py
ideascube/monitoring/tests/test_views.py
ideascube/serveradmin/catalog.py
ideascube/serveradmin/tests/test_catalog.py

The default encoding on Python 3 is the one from the current locale.
This almost always means UTF-8, at least for our target deployment
(Debian Jessie with a UTF-8 locale)
And that's a great thing. It's not necessary to think about encoding
issues most of the time, and that's liberating.
However, BSF manages the boxes in two ways.
The first is to connect to them from their (usually Debian, Ubuntu or
Mint) workstations with SSH, through a bastion. The default
configuration for the SSH client on these OS makes the remote session
use the locale of the local session (usually fr_FR.UTF8).
But on Debian, not all locales are installed by default. This means that
the remote session will try to use a locale (from the local session)
which is not installed on the server.
When that happens, the …

Use a non-UTF8 locale to run the tests

---

ideascube/serveradmin/catalog.py

Not all zim come with a corresponding index.
If there is no index file, we should not add it to library xml.

Check that index file is really present before adding it to library.xml

---

ideascube/management/commands/tags.py
ideascube/mediacenter/models.py
ideascube/search/models.py
ideascube/search/tests/test_models.py
ideascube/tests/test_tags_command.py
ideascube/tests/test_utils.py
ideascube/utils.py

Before ideascube version 0.9, we were using case-sensitive taggit.
Then at this time, taggit were creating two different tags for 'Foo' and
'foo'.
But now, with more recent versions, we are in case-insensitive. Then
taggit assumes there is only one tag for a (insensitive) string.
So if we try to tag a object with tag 'foo', taggit crashes because the
assumption is not fulfill.
This new command "tags sanitize" fixes this by merging (insensitive) equal
tags. After running it, we end with the same situation as if we were all
the time in case-insensitive setting.
This command also clean the tag names. It remove punctuation characters and
remove tags with empty names.

Add a command to clean tags.

---

ideascube/conf/idb_col_llavedelsaber.py
ideascube/forms.py
ideascube/templates/ideascube/user_import.html
ideascube/tests/test_import_users.py
ideascube/tests/test_settings.py

I had to take a bit of a detour in order to do this the way we wanted.
First, this branch introduces a new widget, the ComboBoxEntry, which is inexplicably absent from HTML.
Second, the `current_occupation` and `school_level` fields of the `User` model are changed to accept any value, but use the ComboBoxEntry as a widget so that we still show a default list to try and guide users towards always using the same values. Custom values get added to the list the first time they are used.
Third, a few of these values are added or renamed, as we found the current lists weren't perfect.
Finally, the user import process is made to optionally accept data in the Llave del Saber format, and try mapping their values to ours when it makes sense.
Relates to #662

Import from Llave del Saber

---

Makefile
requirements-dev.txt
requirements.txt

pip-compile doesn't support URLs as packages unless they are editable.
So we need the '-e' options in *.in files.
But, then when dh-virtualenv	install the package as editable with a
egg-link pointing to the source. As the sources change location when we
package everything, the egg-link points to nothing and we cannot import
the packages.
This is a bit silly, but the sed after the requirements.txt generation
removes the '-e' option and everything work again.
This is definitively a workaround and we should remove it once this bug is
fixed : https://github.com/spotify/dh-virtualenv/issues/200

Remove -e in requirements(-dev).txt

---

ideascube/conf/kb_bfa_bsfcampus.py

Actually a simple copy of `kb_bsfcampus_sen.py` relocated to Burkina Faso.

Configuration for kb_bfa_bsfcampus.

---

ideascube/serveradmin/catalog.py

See individual commits.
The second one deserves some discussion though. It seems to fix the issue, and I can then view the imported media files in the mediacenter.
However, I'm not sure of the implications this might have on everything else.
@mgautierfr Please review carefully. Especially since you wrote this code and know better its ins-and-outs.

Some fixes for the catalog/mediacenter interaction

---

ideascube/conf/base.py

Django 1.10 introduced a new way to make middlewares, and to avoid
breaking compatibility they added the MIDDLEWARE setting to enable them.
Django's built-in middlewares are all compatible with both the old and
new ways, and therefore can be used with either MIDDLEWARE or
MIDDLEWARE_CLASSES.
However, one can assume that the old way will eventually get removed, so
we need to move to the new way eventually.
Fortunately, we only use Django's builtin middlewares, we don't have any
custom ones, so we only have to actually switch to the new setting. :)
https://docs.djangoproject.com/en/1.10/topics/http/middleware/

Move to the new MIDDLEWARE setting

---

requirements-dev.txt
requirements.in
requirements.txt

The latest releases are giving us trouble. Version 2.0.0 is a full
rewrite, which seems to have broken compatibility with the old
NetworkManager on Debian Jessie.
Git master has a patch to restore compatibility:
https://github.com/seveas/python-networkmanager/commit/cad4dc79efd8d29e9fe1f1cd03f76e61534af808
However, even with that applied we still seem to encounter issues. So
for now, we've decided to stick with the older version.

Downgrade our python-NetworkManager dependency
