ideascube/ideascube

serveradmin/tests/test_serveradmin.py

Always mock subprocess call to services in unittests

---

.travis.yml

New container based Travis build

---

ideasbox/conf/base.py
ideasbox/conf/mapoon.py
ideasbox/models.py

Asked by Sylvain, currently installing a box in Australia, not in a camp.
@magopian @davidbgk @providenz, quick r? :)

Allow to define the ideasbox place name per settings (cf #151)

---

ideasbox/conf/base.py
ideasbox/conf/mapoon.py
ideasbox/monitoring/tests/test_views.py
ideasbox/monitoring/views.py

Ref #150
For the Mapoon project, currently boostraping in Australia.

Allow to define the default loan duration in settings (fix #150)

---

pytest.ini

This is a useful indication as to which parts of the code might need
more unit tests.

tests: Show which lines are not covered

---

ideascube/static/ideascube/js/ideascube.js

SSIA.
Found those while working on the wifi feature.

A few eslint-related fixes

---

ideascube/serveradmin/tests/test_wifi.py
ideascube/serveradmin/wifi.py

NetworkManager allows creating a new connection either for just the current user, or shared with all other users on the system.
Before this commit, we were doing the latter, which requires additional permissions.
Since we only really care about the ideascube user, let's only create a connection for that user.

wifi: Properly handle users making mistakes with the Wi-Fi key

---

ideascube/mediacenter/management/commands/import_medias.py

Refs #203
Mnémotechnique UnicodeDecode et UnicodeEncode errors.
"Quand je rentre je DEfait mon manteau, quand je pars j'ENfile mon manteau"

Handle UnicodeDecode error during CSV importation. (Fixes #203)

---

ideascube/serveradmin/tests/__init__.py
ideascube/serveradmin/wifi.py

Allow connecting to WPA2 networks

---

debian/changelog

https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version
https://www.debian.org/doc/debian-policy/footnotes.html#f37

debian: Use tilde to indicate the pre-release

---

ideascube/serveradmin/templates/serveradmin/wifi.html
ideascube/serveradmin/tests/__init__.py
ideascube/serveradmin/wifi.py

Last commit is a bit of a straw proposal for fixing the issue right now, but it clearly isn't how we should fix it in the long term.

A few Wifi fixes

---

debian/control
debian/uwsgi/ideascube.ini

Fix some more Python 3 stuff

---

Makefile
docs/contributing.md

These modifications are based on my experiment to run ideascube into docker.

Python3 makefile

---

ideascube/management/utils.py
ideascube/mediacenter/management/commands/import_medias.py
ideascube/mediacenter/tests/test_import_medias.py

More granular reporting for import_medias (fix #275 fix #276)

---

ideascube/mediacenter/migrations/0004_auto_20160211_1450.py
ideascube/mediacenter/models.py

Add epub type in mediacenter (fix #282)

---

ideascube/conf/kb_rca_alliancefrancaise.py

Disable BSF Campus for RCA Alliance Française

---

ideascube/conf/kb_rca_alliancefrancaise.py

The goal was to disable BSF Campus, not prevent the server from starting.

Fix previous configuration change

---

ideascube/conf/base.py
ideascube/mediacenter/management/commands/tags.py
ideascube/tests/test_tags_command.py

[WIP] Basic tags management command

---

ideascube/blog/forms.py
ideascube/fields.py
ideascube/library/forms.py
ideascube/mediacenter/forms.py
ideascube/mediacenter/tests/test_views.py

Add lang code in lang select (fix #321)

---

ideascube/mediacenter/tests/test_views.py
ideascube/templatetags/ideascube_tags.py

Reset page parameter when changing search filters (fix #364)

---

ideascube/settings.py
manage.py

This pull request makes it so that we don't ignore configuration errors any more.
In addition, we now fallback on the base config, not the development one.
Relates to #373

Settings changes

---

.travis.yml

Travis will be run in PRs anyway. But just once, from now on :)

Only run Travis on commits on master branch

---

ideascube/serveradmin/backup.py
ideascube/serveradmin/tests/test_backup.py

Backup do not save symlink

---

conftest.py
ideascube/serveradmin/tests/conftest.py
ideascube/serveradmin/tests/test_backup.py
ideascube/serveradmin/tests/test_catalog.py
ideascube/serveradmin/tests/test_catalog_command.py
ideascube/serveradmin/tests/test_views.py
pytest.ini

Temporary dirs for all the tests

---

conftest.py
ideascube/conf/base.py
ideascube/conf/dev.py
ideascube/serveradmin/catalog.py
ideascube/serveradmin/tests/test_catalog.py
ideascube/serveradmin/tests/test_catalog_command.py
ideascube/settings.py

Fixes #376 
I strongly suggest you review this one commit at a time, as it will make it much easier to grasp the changes. :wink:

Split catalog cache

---

ideascube/serveradmin/catalog.py
ideascube/serveradmin/management/commands/catalog.py
ideascube/serveradmin/tests/test_catalog.py
ideascube/serveradmin/tests/test_catalog_command.py

Catalog do not fail when listing with a unknown type package.

---

ideascube/static/ideascube/main.css

Before the commits:
After the commit:
During the commit (waiting for the house keys under 53° Celsius (yeah I mean Celsius) ;)

Fix some rtl alignments

---

debian/control
debian/rules
requirements-dev.txt
requirements.txt

Deps, build deps and build

---

ideascube/templates/ideascube/user_list.html
ideascube/tests/test_views.py

Display correct users count in users list (fix #419)

---

ideascube/search/apps.py
ideascube/search/migrations/0001_initial.py
ideascube/search/migrations/0002_drop_old_index_table.py
ideascube/search/utils.py

See each commit for rationale.

Be smarter about when to reindex the database

---

ideascube/conf/idb_grc_malakasa.py

Dirty conf file needs more love!

Idb grc malakasa

---

.coveragerc
ideascube/blog/forms.py
ideascube/fields.py
ideascube/forms.py
ideascube/library/forms.py
ideascube/mediacenter/forms.py
ideascube/serveradmin/templates/serveradmin/wifi.html
ideascube/serveradmin/templates/serveradmin/wifi_history.html
ideascube/serveradmin/tests/test_backup.py
ideascube/serveradmin/tests/test_catalog.py
ideascube/serveradmin/views.py
ideascube/static/ideascube/main.css
ideascube/tests/test_settings.py
ideascube/tests/test_views.py
ideascube/utils.py
ideascube/widgets.py

These are some small things that I stumbled upon while working on the in-database configuration system and redoing the content language management.
Most of them already are in the #427 pull request. I'm pushing them separately to make the other one smaller, and get those things reviewed/merged earlier, without having to wait for #427 which will take a bit more time.

Miscellaneous things

---

ideascube/serveradmin/catalog.py

We were assuming too much about the structure of zipped zim packages.
Specifically, for a package downloaded at:
http://download.kiwix.org/portable/other/kiwix-0.9+bouquineux_fr_all_2013-07.zip
We assumed that the zim files inside it would always be named:  `bouquineux_fr_all_2013-07.zim*`
But that's not the case, they were named: `bouquineux_07_2013.zim*`
This commit drops that assumption, and instead tries harder to find the zim files as they are named.

catalog: Fix some broken assumptions

---

ideascube/serveradmin/templates/serveradmin/wifi.html

Fix wifi modal broken since 3f78876b6ab5de206ce61d19e3fd1035e1fbc6e7

Fix wifi modal broken since 3f78876b6ab5de206ce61d19e3fd1035e1fbc6e7

---

ideascube/conf/idb_bsf_demoserver.py

Since this is the demo server, all the staff apps must be available.

library application added

---

ideascube/conf/idb_jor_alhashmi.py
ideascube/conf/idb_jor_azraq.py
ideascube/conf/kb_jor_croixrouge.py

This also impacts Al-Hashmi, that's on purpose.

Reboot Azraq config

---

ideascube/mediacenter/templates/mediacenter/document_detail.html

Display pdf/audio preview if any in document page

---

ideascube/context_processors.py
ideascube/templates/base.html
ideascube/templates/ideascube/includes/js.html
ideascube/tests/test_views.py
ideascube/urls.py
ideascube/views.py

Well, not just caching, see each commit for details.
Fixes #469

Dynamic js caching

---

ideascube/conf/base.py
ideascube/models.py
ideascube/templatetags/ideascube_tags.py
ideascube/tests/test_views.py
requirements.txt

Fix deprecation warnings

---

extras/nginx/ideascube
ideascube/blog/templates/blog/content_card.html
ideascube/library/templates/library/book_card.html
ideascube/library/templates/library/book_detail.html
ideascube/mediacenter/forms.py
ideascube/mediacenter/models.py
ideascube/mediacenter/templates/mediacenter/document_card.html
ideascube/mediacenter/templates/mediacenter/document_detail.html
ideascube/mediacenter/templates/mediacenter/oembed.html
ideascube/mediacenter/templatetags/mediacenter_tags.py
ideascube/mediacenter/tests/test_views.py
ideascube/templates/ideascube/includes/blog_card.html
ideascube/templates/ideascube/includes/book_card.html
ideascube/templates/ideascube/includes/document_card.html
ideascube/templatetags/ideascube_tags.py

See each commit for the details.
Fixes #468

Medias improvements

---

conftest.py
ideascube/tests/test_views.py

Here few fixes/improvements.
No special bugs associated to them, but stuff I found while coding :)

Small fixes

---

debian/ideascube.default
ideascube/conf/base.py
ideascube/conf/idb_bsf_demoserver.py
ideascube/conf/kb.py

Static and debug

---

ideascube/conf/idb_jor_zaatari.py

Add configuration for Zaatari, Jordan.

---

ideascube/mediacenter/forms.py

Django offers no guarantee of the order in which the fields of a form
are cleaned.
As a result, we can't have a clean_foo method relying on the fact that
another field bar has already been cleaned.
For this kind of cases, we must use the clean method, which is what
wenow do with this commit.

Don't rely on an unguaranteed order

---

ideascube/configuration/__init__.py
ideascube/configuration/management/commands/config.py
ideascube/configuration/registry.py
ideascube/configuration/tests/test_command_config.py
ideascube/configuration/tests/test_main_api.py
ideascube/configuration/tests/test_registry.py

A CLI to manage the in-database configurations

---

ideascube/serveradmin/views.py

admin: Notify after changing the server name

---

ideascube/library/templates/library/book_detail.html
ideascube/static/ideascube/main.css
ideascube/templates/ideascube/includes/cards/appinventor.html
ideascube/templates/ideascube/includes/cards/blog.html
ideascube/templates/ideascube/includes/cards/bsfcampus.html
ideascube/templates/ideascube/includes/cards/clickinfosn.html
ideascube/templates/ideascube/includes/cards/cpassorcier.old.html
ideascube/templates/ideascube/includes/cards/custom.html
ideascube/templates/ideascube/includes/cards/gutenberg.old.html
ideascube/templates/ideascube/includes/cards/khanacademy.html
ideascube/templates/ideascube/includes/cards/kiwix.html
ideascube/templates/ideascube/includes/cards/koombookedu.html
ideascube/templates/ideascube/includes/cards/library.html
ideascube/templates/ideascube/includes/cards/maps.html
ideascube/templates/ideascube/includes/cards/media-package.html
ideascube/templates/ideascube/includes/cards/mediacenter.html
ideascube/templates/ideascube/includes/cards/software.html
ideascube/templates/ideascube/includes/cards/ted.old.html
ideascube/templates/ideascube/includes/cards/ubuntudoc.old.html
ideascube/templates/ideascube/includes/cards/vikidia.old.html
ideascube/templates/ideascube/includes/cards/w2eu.html
ideascube/templates/ideascube/includes/cards/wikipedia.old.html
ideascube/templates/ideascube/includes/cards/wikisource.old.html

fixed card long title display

---

ideascube/templates/ideascube/welcome_staff.html

Commit 4e9a7592662e5eb9a5ade178a0f6e7f53e566586 moved the submit buttons
around for pretty much all forms, but forgot to remove the old button
for this one.

Remove duplicate submit button

---

ideascube/configuration/registry.py
ideascube/serveradmin/management/commands/reset_home.py
ideascube/serveradmin/tests/test_command_reset_home.py

While I was at this, I found a pretty horrible bug in the config app, so that's fixed in this pull request as well.

Cards for old packages

---

ideascube/library/views.py
ideascube/models.py
ideascube/monitoring/forms.py
ideascube/monitoring/models.py
ideascube/tests/test_views.py

Also replaces "serial" by "identifier", because it was a bad naming.

added gettext where missing

---

ideascube/fields.py

Replacing multiple select combo box by a list of checkboxes

CommaSeparatedCharField is now checkboxes by default

---

ideascube/library/templates/library/specimen_form.html

focus on a serial for form on a new specimen

---

ideascube/templates/ideascube/by_tag.html
ideascube/templates/ideascube/includes/tag_cloud.html

Rename 'theme' to 'topic' as it can be ambiguous with "site appearance".

---

ideascube/blog/models.py
ideascube/library/models.py
ideascube/mediacenter/models.py
ideascube/models.py
ideascube/monitoring/models.py

explicit use of verbose_name

---

ideascube/conf/idb_col_llavedelsaber.py

We are talking about the country, not the spaceship, neither the...
https://en.wikipedia.org/wiki/Columbia

Fix Colombia name.

---

ideascube/blog/models.py
ideascube/blog/tests/test_views.py
ideascube/blog/views.py

Preset blog post with current user and current date

---

debian/control
debian/ideascube.lintian-overrides
debian/ideascube.postinst
debian/ideascube.postrm
debian/rules
debian/source.lintian-overrides

Following on the steps of #583, this is another set of commits extracted from #341 which should not require any coordination with ansiblecube.
As previously, I just cherry-picked the commits, I didn't change anything.
The only one which actually changes something important is the last one about cleaning our stuff up when we leave, but it shouldn't cause any problem.

Packaging improvements

---

ideascube/monitoring/templates/monitoring/stock.html

stock: Avoid overly long descriptions

---

ideascube/serveradmin/catalog.py
ideascube/serveradmin/tests/test_catalog.py

This fixes #513.
It also includes a few things I found while working on it.
Let me know if you want me to separate them into their own pull request.

catalog: Update the installed metadata

---

extras/nginx/ideascube
ideascube/conf/base.py
ideascube/conf/idb.py
ideascube/conf/idb_col_llavedelsaber.py

This also makes "ideascube.lan" the default domain.
closes #500

Add bibliotecamovil.lan

---

ideascube/forms.py
ideascube/library/tests/test_utils.py
ideascube/library/utils.py
ideascube/templates/ideascube/user_import.html
ideascube/templates/ideascube/user_list.html
ideascube/tests/test_import_users.py
ideascube/tests/test_utils.py
ideascube/urls.py
ideascube/utils.py
ideascube/views.py

Import users

---

ideascube/library/tests/test_views.py
ideascube/library/views.py

Add a warning to staff user if there is no specimen for a book.

---

.travis.yml
Makefile
conftest.py
ideascube/configuration/migrations/0002_settings_to_configuration.py
ideascube/db_router.py
ideascube/library/migrations/0008_library_stock.py
ideascube/migrations/0009_add_a_system_user.py
ideascube/models.py
ideascube/search/apps.py
ideascube/search/migrations/0001_initial.py
ideascube/search/migrations/0002_drop_old_index_table.py
ideascube/search/models.py
ideascube/tests/test_models.py

Be able to run test with migration or not.
The default (run without migration) is not changed.

Test with migration

---

ideascube/conf/kb_rwa_giz.py

Can you review and merge ? 
Thanks

Kb rwa giz

---

ideascube/library/models.py
ideascube/library/templates/library/index.html
ideascube/library/tests/test_views.py
ideascube/library/views.py
ideascube/search/templates/search/filter_by_kind.html

This PR is base on the PR #619 as we need the new section field.
Fix #599.

Section search

---

requirements-dev.txt
requirements.txt

Upgrading factory-boy fixes the build:
https://github.com/FactoryBoy/factory_boy/issues/334
But while we're at it, we might as well upgrade everything.

Upgrade our deps

---

ideascube/monitoring/templates/monitoring/inventory.html

Add the serial number column in the inventory view.

---

ideascube/conf/idb_col_llavedelsaber.py

After discussion, this is not something we will have in Ideascube.
Fixes #609

Stop using the extra field for Colombia

---

docs/release_process.md
docs/translate.md

This is based on notes from @yohanboniface.
It's certainly not perfect, but it's a pretty decent beginning.

Document our release process

---

ideascube/__init__.py

Refuse to run on Python 2

---

ideascube/serveradmin/catalog.py

Setting category for "bouquineux" as "READ".

---

ideascube/conf/idb_rwa_mahama.py

Correct me if needed :)
We may completely remove the blog from ideascube. We need to talk about that with @barbayellow .

Removing blog on idb_rwa_mahama

---

ideascube/monitoring/forms.py
ideascube/monitoring/templates/monitoring/inventory.html
ideascube/monitoring/templates/monitoring/stock.html
ideascube/monitoring/tests/test_views.py

The PR #672 is not ready yet.
However, there are some interesting changes we want to have right now.
This PR just cherry-pick interesting commits of #672.

Serial intermediate pr

---

extras/nginx/ideascube

Can it be merge in the next release ? 
Thanks

Increase upload max file size on Nginx

---

ideascube/conf/idb_jor_hostcommunity.py

Narjis says the hostcommunity conf should import its USER_FORM_FIELDS
from alhashmi instead of azraq's ones.

Fix for idb_jor_hostcommunity user form fields.

---

ideascube/mediacenter/management/commands/clean.py
ideascube/mediacenter/tests/test_clean.py

Media installed with a package are not removed.
Fix partially #685.

Add a command to remove all media from the mediacenter.

---

ideascube/conf/base.py
ideascube/mediacenter/models.py
ideascube/mediacenter/templates/mediacenter/index.html
ideascube/static/ideascube/main.css
ideascube/templates/ideascube/includes/tag_cloud.html
ideascube/tests/test_utils.py
ideascube/utils.py

Several small commits on the mediacenter to improve it.
Fixes few already opened bugs.

Mediacenter misc

---

ideascube/conf/idb_irq_bardarash.py

Modification has been done directly on the server.
Can it merged on the next release  ?

Remove Kalite until Arabic language is available

---

.coveragerc
Makefile

Just a few little things that were bugging me, and which I came upon while working on the CI. (a future pull request)

Misc dev things

---

.coveragerc
ideascube/tests/test_settings.py

This isn't much, just some stuff I found while working on #691

Some minor test improvements

---

ideascube/mediacenter/utils.py
ideascube/serveradmin/catalog.py

Improvements to media packages

---

debian/ideascube.lintian-overrides
extras/bin/ideascube
extras/uwsgi/ideascube.ini

http://dh-virtualenv.readthedocs.io/en/latest/info.html#id1

Adapt to the new dh-virtualenv root folder

---

ideascube/conf/kb_cod_kinlab.py

Add specific conf file for kb_cod_kinlab

---

Makefile
docs/release_process.md
ideascube/models.py
ideascube/monitoring/models.py

Some small things I encountered while working on migration testing in the CI.
See the individual commits for details.

Misc model stuff

---

ideascube/configuration/management/commands/config.py
ideascube/configuration/tests/test_command_config.py
ideascube/management/base.py
ideascube/management/commands/tags.py
ideascube/mediacenter/management/commands/clean.py
ideascube/serveradmin/management/commands/catalog.py
ideascube/serveradmin/tests/test_catalog_command.py
ideascube/tests/test_command_base.py

Less code, better test coverage, what's not to like?

Factorize some command-related code

---

docs/release_process.md

Now that we have had a release tag with test data, we can use the
make target as intended.

docs: Update the release process

---

ideascube/blog/tests/test_views.py
ideascube/library/tests/test_views.py
ideascube/mediacenter/tests/test_views.py
ideascube/tests/test_views.py
requirements-dev.txt
requirements.txt

The new WebTest is being annoying, so while fixing it (in the second commit), I used this occasion of better passing some querystrings that I found. (in the first commit)

Upgrade our dependencies

---

ideascube/conf/idb.py
ideascube/conf/idb_irq_bardarash.py

There already is no card pointing to the battery page, so why try
hiding it?

Remove unnecessary setting

---

ideascube/serveradmin/catalog.py

Chomp chomp chomp chomp chomp.
Chomp CHOMP!

Chomp chomp

---

ideascube/management/args.py
ideascube/mediacenter/management/commands/clean.py
ideascube/mediacenter/tests/test_clean.py
ideascube/tests/test_command_args.py

Media cleanup with filters
